version: "3"

services:
  train:
    container_name: horovod-pytorch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./timeline:/workspace/timeline
      - ./logs:/workspace/logs
      - ~/.ssh:/root/.ssh
      - ./cifar10/cifar10:/root/imagenet/cifar10
    network_mode: "host"
