version: "3"

services:
  train:
    container_name: horovod-pytorch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./timeline:/workspace/timeline
      - ~/.ssh:/root/.ssh
    network_mode: "host"
